const PDFDocument = require('pdfkit');
const { Student, AssessmentScore, Subject, ClassStream } = require('../models');

exports.downloadReportCard = async (req, res) => {
  try {
    const { studentId } = req.params;
    const student = await Student.findByPk(studentId, {
      include: [
        { model: ClassStream, as: 'classStream' },
        { model: AssessmentScore, as: 'assessments', include: [{ model: Subject, as: 'subject' }] },
      ],
    });

    if (!student) {
      return res.status(404).json({ message: 'Student not found' });
    }

    const doc = new PDFDocument({ margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${student.firstName}_report_card.pdf`);
    doc.pipe(res);

    doc.fontSize(20).text('STUDENT REPORT CARD', { align: 'center' }).moveDown();
    doc.fontSize(12)
      .text(`Name: ${student.firstName} ${student.lastName}`)
      .text(`Admission Number: ${student.admissionNumber}`)
      .text(`Class: ${student.classStream.form} ${student.classStream.stream}`)
      .moveDown();

    doc.fontSize(12)
      .text('Subject', 50, doc.y)
      .text('CA', 200, doc.y)
      .text('Exam', 260, doc.y)
      .text('Total', 320, doc.y)
      .text('Grade', 380, doc.y);
    doc.moveDown();

    let totalScore = 0;
    student.assessments.forEach((assessment) => {
      totalScore += Number(assessment.totalScore || 0);
      doc.fontSize(10)
        .text(assessment.subject.name, 50)
        .text(assessment.continuousAssessmentScore, 200)
        .text(assessment.examScore, 260)
        .text(assessment.totalScore, 320)
        .text(assessment.grade, 380);
    });

    doc.moveDown();
    const average = student.assessments.length > 0 ? (totalScore / student.assessments.length).toFixed(2) : 0;
    doc.fontSize(12)
      .text(`Total Score: ${totalScore}`)
      .text(`Average: ${average}`);

    doc.moveDown();
    doc.fontSize(10).text('Generated by School Management System', { align: 'center' });
    doc.end();
  } catch (error) {
    res.status(500).json({ message: 'Server Error', error: error.message });
  }
};

exports.downloadClassPerformanceReport = async (req, res) => {
  try {
    const { classStreamId } = req.params;
    const classStream = await ClassStream.findByPk(classStreamId, {
      include: [
        {
          model: Student,
          as: 'students',
          include: [
            {
              model: AssessmentScore,
              as: 'assessments',
              include: [{ model: Subject, as: 'subject' }],
            },
          ],
        },
      ],
    });

    if (!classStream) {
      return res.status(404).json({ message: 'Class stream not found' });
    }

    const students = classStream.students.map((student) => {
      const totalScore = student.assessments.reduce((sum, a) => sum + Number(a.totalScore || 0), 0);
      const count = student.assessments.length;
      const average = count ? totalScore / count : 0;
      return {
        id: student.id,
        name: `${student.firstName} ${student.lastName}`,
        admissionNumber: student.admissionNumber,
        totalScore,
        average: average.toFixed(2),
      };
    });

    const rankedStudents = students
      .sort((a, b) => b.totalScore - a.totalScore)
      .map((student, index) => ({ rank: index + 1, ...student }));

    const subjectStats = {};
    classStream.students.forEach((student) => {
      student.assessments.forEach((assessment) => {
        const subjectName = assessment.subject.name;
        if (!subjectStats[subjectName]) {
          subjectStats[subjectName] = {
            subject: subjectName,
            totalScore: 0,
            count: 0,
            highest: Number(assessment.totalScore || 0),
            lowest: Number(assessment.totalScore || 0),
          };
        }
        subjectStats[subjectName].totalScore += Number(assessment.totalScore || 0);
        subjectStats[subjectName].count += 1;
        subjectStats[subjectName].highest = Math.max(subjectStats[subjectName].highest, Number(assessment.totalScore || 0));
        subjectStats[subjectName].lowest = Math.min(subjectStats[subjectName].lowest, Number(assessment.totalScore || 0));
      });
    });

    const subjectSummaries = Object.values(subjectStats).map((stat) => ({
      subject: stat.subject,
      average: stat.count ? (stat.totalScore / stat.count).toFixed(2) : '0.00',
      highest: stat.highest,
      lowest: stat.lowest,
    }));

    const classAverage = rankedStudents.length
      ? (
          rankedStudents.reduce((sum, student) => sum + Number(student.average || 0), 0) /
          rankedStudents.length
        ).toFixed(2)
      : '0.00';

    const doc = new PDFDocument({ margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${classStream.form}_${classStream.stream}_performance.pdf`);
    doc.pipe(res);

    doc.fontSize(20).text('CLASS PERFORMANCE REPORT', { align: 'center' }).moveDown();
    doc.fontSize(12)
      .text(`Class: ${classStream.form} ${classStream.stream}`)
      .text(`Generated: ${new Date().toLocaleDateString()}`)
      .moveDown();

    doc.fontSize(14).text('Overall Summary').moveDown(0.5);
    doc.fontSize(12)
      .text(`Student Count: ${rankedStudents.length}`)
      .text(`Class Average Score: ${classAverage}`)
      .moveDown();

    doc.fontSize(14).text('Student Rankings').moveDown(0.5);
    doc.fontSize(10).text('Rank  Name                                Total   Average');
    rankedStudents.forEach((student) => {
      doc.text(
        `${student.rank.toString().padEnd(5)} ${student.name.padEnd(35)} ${student.totalScore.toString().padEnd(7)} ${student.average}`
      );
    });
    doc.moveDown();

    doc.fontSize(14).text('Subject Performance').moveDown(0.5);
    doc.fontSize(10).text('Subject                          Average   High   Low');
    subjectSummaries.forEach((subject) => {
      doc.text(
        `${subject.subject.padEnd(30)} ${subject.average.toString().padEnd(9)} ${subject.highest.toString().padEnd(6)} ${subject.lowest}`
      );
    });

    doc.moveDown();
    doc.fontSize(10).text('Generated by School Management System', { align: 'center' });
    doc.end();
  } catch (error) {
    res.status(500).json({ message: 'Server Error', error: error.message });
  }
};
