const PDFDocument = require('pdfkit');
const { Student, AssessmentScore, Subject, ClassStream } = require('../models');


// ============================
// GENERATE REPORT CARD PDF
// ============================
exports.downloadReportCard = async (req, res) => {
  try {
    const { studentId } = req.params;

    const student = await Student.findByPk(studentId, {
      include: [
        {
          model: ClassStream,
          as: 'classStream'
        },
        {
          model: AssessmentScore,
          as: 'assessments',
          include: [
            {
              model: Subject,
              as: 'subject'
            }
          ]
        }
      ]
    });

    if (!student) {
      return res.status(404).json({
        message: 'Student not found'
      });
    }

    // =========================
    // CREATE PDF DOCUMENT
    // =========================
    const doc = new PDFDocument({ margin: 50 });

    // headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename=${student.firstName}_report_card.pdf`
    );

    doc.pipe(res);

    // =========================
    // SCHOOL HEADER
    // =========================
    doc
      .fontSize(20)
      .text('STUDENT REPORT CARD', { align: 'center' })
      .moveDown();

    doc
      .fontSize(12)
      .text(`Name: ${student.firstName} ${student.lastName}`)
      .text(`Admission Number: ${student.admissionNumber}`)
      .text(
        `Class: ${student.classStream.form} ${student.classStream.stream}`
      )
      .moveDown();

    // =========================
    // TABLE HEADER
    // =========================
    doc
      .fontSize(12)
      .text('Subject', 50, doc.y)
      .text('CA', 200, doc.y)
      .text('Exam', 260, doc.y)
      .text('Total', 320, doc.y)
      .text('Grade', 380, doc.y);

    doc.moveDown();

    // =========================
    // SUBJECTS DATA
    // =========================
    let totalScore = 0;

    student.assessments.forEach((a) => {
      totalScore += Number(a.totalScore || 0);

      doc
        .fontSize(10)
        .text(a.subject.name, 50)
        .text(a.continuousAssessmentScore, 200)
        .text(a.examScore, 260)
        .text(a.totalScore, 320)
        .text(a.grade, 380);
    });

    doc.moveDown();

    // =========================
    // SUMMARY
    // =========================
    const average =
      student.assessments.length > 0
        ? (totalScore / student.assessments.length).toFixed(2)
        : 0;

    doc
      .fontSize(12)
      .text(`Total Score: ${totalScore}`)
      .text(`Average: ${average}`);

    // =========================
    // FOOTER
    // =========================
    doc.moveDown();
    doc.fontSize(10).text('Generated by School Management System', {
      align: 'center'
    });

    doc.end();

  } catch (error) {
    res.status(500).json({
      message: 'Server Error',
      error: error.message
    });
  }
};